apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: default
  namespace: default
spec:
  # Everything from this repo will be ran in this cluster. You trust me right?
  repo: "https://github.com/sourabh3b/fleet-example"
  branch: main
  paths:
  - dedicated/base/ako